package project;

import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author spring2018
 */
public class LibrarianDashboard extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    public LibrarianDashboard() throws SQLException {
        initComponents();
        ManageLibParks lp = new ManageLibParks();
        lp.timechecker();
        Vip v = new Vip();
        v.vipended();
        Defaulter d = new Defaulter();
        d.addstudent();
        updatestats();
        time();
    }

    public void time() {
        DateFormat dateFormat = new SimpleDateFormat("hh:mm aa");
        String dateString = dateFormat.format(new Date());
        timelbl.setText(dateString);
    }

    public void updatestats() throws SQLException {
        Student student = new Student();
        totalstudents.setText(student.countstudents());
        Vip vip = new Vip();
        totalvips.setText(vip.countstudents());
        Defaulter d = new Defaulter();
        d.addstudent();
        totaldefaulters.setText(d.countstudents());
        Book b = new Book();
        mostreadgenrelbl.setText(b.mostreadgenre());
        mostreadbooklbl.setText(b.mostreadbook());
        totalbookslbl.setText(b.countbooks());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton13 = new javax.swing.JButton();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jPanel11 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        fillbtn = new javax.swing.JButton();
        fillbtn1 = new javax.swing.JButton();
        fillbtn5 = new javax.swing.JButton();
        fillbtn8 = new javax.swing.JButton();
        fillbtn9 = new javax.swing.JButton();
        fillbtn10 = new javax.swing.JButton();
        fillbtn11 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        fillbtn12 = new javax.swing.JButton();
        timelbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        totalstudents = new javax.swing.JTextField();
        totalbookslbl = new javax.swing.JTextField();
        totalvips = new javax.swing.JTextField();
        mostreadgenrelbl = new javax.swing.JTextField();
        totaldefaulters = new javax.swing.JTextField();
        mostreadbooklbl = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        jButton13.setBackground(new java.awt.Color(255, 102, 0));
        jButton13.setText("MANAGE BOOKS");
        jButton13.setBorder(null);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0)));

        fillbtn.setBackground(new java.awt.Color(0, 0, 0));
        fillbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fillbtn.setForeground(new java.awt.Color(255, 255, 255));
        fillbtn.setText("M A N A G E  S T U D E N T S");
        fillbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 4));
        fillbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fillbtn.setHideActionText(true);
        fillbtn.setRolloverEnabled(false);
        fillbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillbtnActionPerformed(evt);
            }
        });

        fillbtn1.setBackground(new java.awt.Color(0, 0, 0));
        fillbtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fillbtn1.setForeground(new java.awt.Color(255, 255, 255));
        fillbtn1.setText("M A N A G E  B O O K S");
        fillbtn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 4));
        fillbtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fillbtn1.setHideActionText(true);
        fillbtn1.setRolloverEnabled(false);
        fillbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillbtn1ActionPerformed(evt);
            }
        });

        fillbtn5.setBackground(new java.awt.Color(0, 0, 0));
        fillbtn5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fillbtn5.setForeground(new java.awt.Color(255, 255, 255));
        fillbtn5.setText("M A N A G E  V I P s");
        fillbtn5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 4));
        fillbtn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fillbtn5.setHideActionText(true);
        fillbtn5.setRolloverEnabled(false);
        fillbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillbtn5ActionPerformed(evt);
            }
        });

        fillbtn8.setBackground(new java.awt.Color(0, 0, 0));
        fillbtn8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fillbtn8.setForeground(new java.awt.Color(255, 255, 255));
        fillbtn8.setText("S T U D E N T  F E E D B A C K S");
        fillbtn8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 4));
        fillbtn8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fillbtn8.setHideActionText(true);
        fillbtn8.setRolloverEnabled(false);
        fillbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillbtn8ActionPerformed(evt);
            }
        });

        fillbtn9.setBackground(new java.awt.Color(0, 0, 0));
        fillbtn9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fillbtn9.setForeground(new java.awt.Color(255, 255, 255));
        fillbtn9.setText("M A N A G E  L I B R A R Y  P A R K S");
        fillbtn9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 4));
        fillbtn9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fillbtn9.setHideActionText(true);
        fillbtn9.setRolloverEnabled(false);
        fillbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillbtn9ActionPerformed(evt);
            }
        });

        fillbtn10.setBackground(new java.awt.Color(0, 0, 0));
        fillbtn10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fillbtn10.setForeground(new java.awt.Color(255, 255, 255));
        fillbtn10.setText("D E F A U L T E R S '  L I S T S");
        fillbtn10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 4));
        fillbtn10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fillbtn10.setHideActionText(true);
        fillbtn10.setRolloverEnabled(false);
        fillbtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillbtn10ActionPerformed(evt);
            }
        });

        fillbtn11.setBackground(new java.awt.Color(0, 0, 0));
        fillbtn11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fillbtn11.setForeground(new java.awt.Color(255, 255, 255));
        fillbtn11.setText("I S S U E / R E T U R N  B O O K S");
        fillbtn11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 4));
        fillbtn11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fillbtn11.setHideActionText(true);
        fillbtn11.setRolloverEnabled(false);
        fillbtn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillbtn11ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(209, 202, 240));
        jButton3.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("L O G  O U T");
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        fillbtn12.setBackground(new java.awt.Color(0, 0, 0));
        fillbtn12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fillbtn12.setForeground(new java.awt.Color(255, 255, 255));
        fillbtn12.setText("H I S T O R Y");
        fillbtn12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 4));
        fillbtn12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fillbtn12.setHideActionText(true);
        fillbtn12.setRolloverEnabled(false);
        fillbtn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillbtn12ActionPerformed(evt);
            }
        });

        timelbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        timelbl.setForeground(new java.awt.Color(255, 255, 255));
        timelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timelbl.setText("11:56 AM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fillbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fillbtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fillbtn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fillbtn9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fillbtn11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fillbtn8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fillbtn10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fillbtn12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(timelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(timelbl, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fillbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fillbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fillbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fillbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fillbtn11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fillbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fillbtn10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fillbtn12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(17, 17, 17))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(66, 72, 116));
        jLabel2.setText("Library Statistics");

        totalstudents.setEditable(false);
        totalstudents.setBackground(new java.awt.Color(252, 134, 54));
        totalstudents.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalstudents.setForeground(new java.awt.Color(255, 255, 255));
        totalstudents.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalstudents.setText("0000");
        totalstudents.setBorder(null);
        totalstudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalstudentsActionPerformed(evt);
            }
        });

        totalbookslbl.setEditable(false);
        totalbookslbl.setBackground(new java.awt.Color(252, 134, 54));
        totalbookslbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalbookslbl.setForeground(new java.awt.Color(255, 255, 255));
        totalbookslbl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalbookslbl.setText("0000");
        totalbookslbl.setBorder(null);
        totalbookslbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalbookslblActionPerformed(evt);
            }
        });

        totalvips.setEditable(false);
        totalvips.setBackground(new java.awt.Color(252, 134, 54));
        totalvips.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalvips.setForeground(new java.awt.Color(255, 255, 255));
        totalvips.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalvips.setText("0000");
        totalvips.setBorder(null);
        totalvips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalvipsActionPerformed(evt);
            }
        });

        mostreadgenrelbl.setEditable(false);
        mostreadgenrelbl.setBackground(new java.awt.Color(252, 134, 54));
        mostreadgenrelbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mostreadgenrelbl.setForeground(new java.awt.Color(255, 255, 255));
        mostreadgenrelbl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mostreadgenrelbl.setText("Null");
        mostreadgenrelbl.setBorder(null);
        mostreadgenrelbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostreadgenrelblActionPerformed(evt);
            }
        });

        totaldefaulters.setEditable(false);
        totaldefaulters.setBackground(new java.awt.Color(252, 134, 54));
        totaldefaulters.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totaldefaulters.setForeground(new java.awt.Color(255, 255, 255));
        totaldefaulters.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totaldefaulters.setText("0000");
        totaldefaulters.setBorder(null);
        totaldefaulters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totaldefaultersActionPerformed(evt);
            }
        });

        mostreadbooklbl.setEditable(false);
        mostreadbooklbl.setBackground(new java.awt.Color(252, 134, 54));
        mostreadbooklbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mostreadbooklbl.setForeground(new java.awt.Color(255, 255, 255));
        mostreadbooklbl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mostreadbooklbl.setText("Null");
        mostreadbooklbl.setBorder(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(66, 72, 116));
        jLabel3.setText("A D M I N   D A S H B O A R D");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(66, 72, 116));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Total Students ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(66, 72, 116));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Total Books");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(66, 72, 116));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Total VIPs");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(66, 72, 116));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("No. Of Defaulters ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(66, 72, 116));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Most Read Book");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(66, 72, 116));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Most Read Genre");

        jButton5.setBackground(new java.awt.Color(51, 51, 51));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/cross.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setRolloverEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(totaldefaulters)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(mostreadbooklbl))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mostreadgenrelbl)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(totalstudents))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(totalbookslbl))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(totalvips)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jLabel2)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalstudents, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalbookslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalvips, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totaldefaulters, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostreadbooklbl, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostreadgenrelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void totalbookslblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalbookslblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalbookslblActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        LoginPage lp;
        try {
            lp = new LoginPage();
            lp.show();
            dispose();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void totalstudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalstudentsActionPerformed
    }//GEN-LAST:event_totalstudentsActionPerformed

    private void totalvipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalvipsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalvipsActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void fillbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillbtn1ActionPerformed
        ManageBooks mb;
        try {
            mb = new ManageBooks();
            mb.show();
            dispose();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }

    }//GEN-LAST:event_fillbtn1ActionPerformed

    private void fillbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillbtn5ActionPerformed
        ManageVips mv;
        try {
            mv = new ManageVips();
            mv.show();
            dispose();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }

    }//GEN-LAST:event_fillbtn5ActionPerformed

    private void fillbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillbtn8ActionPerformed
        StudentFeedbacks sfb;
        try {
            sfb = new StudentFeedbacks();
            sfb.show();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }

        dispose();     }//GEN-LAST:event_fillbtn8ActionPerformed

    private void totaldefaultersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totaldefaultersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totaldefaultersActionPerformed

    private void fillbtn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillbtn11ActionPerformed
        IssueAndReturn iar;
        try {
            iar = new IssueAndReturn();
            iar.show();
            dispose();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_fillbtn11ActionPerformed

    private void fillbtn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillbtn12ActionPerformed
        History h;
        try {
            h = new History();
            h.show();
            dispose();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_fillbtn12ActionPerformed

    private void fillbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillbtnActionPerformed
        ManageStudent ms;
        try {
            ms = new ManageStudent();
            ms.show();
            dispose();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }

    }//GEN-LAST:event_fillbtnActionPerformed

    private void fillbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillbtn9ActionPerformed
        ManageLibParks lp;
        try {
            lp = new ManageLibParks();
            lp.show();
            dispose();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }

    }//GEN-LAST:event_fillbtn9ActionPerformed

    private void mostreadgenrelblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostreadgenrelblActionPerformed

    }//GEN-LAST:event_mostreadgenrelblActionPerformed

    private void fillbtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillbtn10ActionPerformed
        ManageDefaulters md;
        try {
            md = new ManageDefaulters();
            md.show();
            dispose();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }

    }//GEN-LAST:event_fillbtn10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new LibrarianDashboard().setVisible(true);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fillbtn;
    private javax.swing.JButton fillbtn1;
    private javax.swing.JButton fillbtn10;
    private javax.swing.JButton fillbtn11;
    private javax.swing.JButton fillbtn12;
    private javax.swing.JButton fillbtn5;
    private javax.swing.JButton fillbtn8;
    private javax.swing.JButton fillbtn9;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField mostreadbooklbl;
    private javax.swing.JTextField mostreadgenrelbl;
    private javax.swing.JLabel timelbl;
    private javax.swing.JTextField totalbookslbl;
    private javax.swing.JTextField totaldefaulters;
    private javax.swing.JTextField totalstudents;
    private javax.swing.JTextField totalvips;
    // End of variables declaration//GEN-END:variables
}
