package project;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author MOBIN
 */
public class ManageVips extends javax.swing.JFrame {

    String query = "SELECT vip_id,student_fname,student_lname,student_phone,student_email,student_address,student_sex,duration FROM  vips  JOIN student ON student_id=vip_id";

    public ManageVips() throws SQLException {
        initComponents();
        ManageLibParks lp = new ManageLibParks();
        lp.timechecker();
        Defaulter d = new Defaulter();
        d.addstudent();
        Vip v = new Vip();
        v.vipended();
        printtable();
        idtf.setText("");
        fnametf.setText("");
        lnametf.setText("");
        numtf.setText("");
        addresstf.setText("");
        emailtf.setText("");
        fnametf.setEditable(false);
        lnametf.setEditable(false);
        numtf.setEditable(false);
        addresstf.setEditable(false);
        emailtf.setEditable(false);
    }

    public void printtable() {
        try {
            Cipher cipher = new Cipher();
            Vip vip = new Vip();
            ResultSet result2 = vip.getstudent(query);
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.setRowCount(0);

            while (result2.next()) {
                model.addRow(new String[]{cipher.decode(Integer.toString(result2.getInt(1))), cipher.decode(result2.getString(2)), cipher.decode(result2.getString(3)), cipher.decode(result2.getString(4)), cipher.decode(result2.getString(5)), cipher.decode(result2.getString(6)), cipher.decode(result2.getString(7)), cipher.decode(result2.getString(8))});
            }

            if (model.getRowCount() < 20) {
                model.setRowCount(20);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Something went wrong!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        idlbl = new javax.swing.JLabel();
        emailtf = new javax.swing.JTextField();
        numtf = new javax.swing.JTextField();
        addresstf = new javax.swing.JTextField();
        fnametf = new javax.swing.JTextField();
        lnametf = new javax.swing.JTextField();
        idtf = new javax.swing.JTextField();
        emaillbl = new javax.swing.JLabel();
        addresslbl = new javax.swing.JLabel();
        numlbl = new javax.swing.JLabel();
        genderlbl = new javax.swing.JLabel();
        lnamelbl = new javax.swing.JLabel();
        fnamelbl = new javax.swing.JLabel();
        removebtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fillbtn = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        maleradio = new javax.swing.JRadioButton();
        femaleradio = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        searchtf = new javax.swing.JTextField();
        combobox = new javax.swing.JComboBox<>();
        searchbtn = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        jMenuItem2.setText("jMenuItem2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Vips");
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0)));

        idlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idlbl.setForeground(new java.awt.Color(255, 255, 255));
        idlbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        idlbl.setText("Student I.D :");

        emailtf.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        emailtf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        emailtf.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emailtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtfActionPerformed(evt);
            }
        });

        numtf.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        numtf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        numtf.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        numtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numtfActionPerformed(evt);
            }
        });

        addresstf.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        addresstf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        addresstf.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        addresstf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addresstfActionPerformed(evt);
            }
        });

        fnametf.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        fnametf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fnametf.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        fnametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnametfActionPerformed(evt);
            }
        });

        lnametf.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lnametf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        lnametf.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        lnametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnametfActionPerformed(evt);
            }
        });

        idtf.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        idtf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        idtf.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        idtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtfActionPerformed(evt);
            }
        });

        emaillbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emaillbl.setForeground(new java.awt.Color(255, 255, 255));
        emaillbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        emaillbl.setText("Email :");

        addresslbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addresslbl.setForeground(new java.awt.Color(255, 255, 255));
        addresslbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addresslbl.setText("Address :");

        numlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numlbl.setForeground(new java.awt.Color(255, 255, 255));
        numlbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numlbl.setText("Phone No. :");

        genderlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        genderlbl.setForeground(new java.awt.Color(255, 255, 255));
        genderlbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        genderlbl.setText("Gender  :");

        lnamelbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lnamelbl.setForeground(new java.awt.Color(255, 255, 255));
        lnamelbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lnamelbl.setText("Last Name  :");

        fnamelbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fnamelbl.setForeground(new java.awt.Color(255, 255, 255));
        fnamelbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fnamelbl.setText("First Name  :");

        removebtn.setBackground(new java.awt.Color(255, 102, 0));
        removebtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        removebtn.setForeground(java.awt.Color.white);
        removebtn.setText("R E M O V E");
        removebtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 7));
        removebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removebtn.setRolloverEnabled(false);
        removebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removebtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 204));
        jLabel1.setText("M A N A G E  V I P s");

        fillbtn.setBackground(new java.awt.Color(255, 102, 0));
        fillbtn.setForeground(new java.awt.Color(255, 255, 255));
        fillbtn.setText("F I L L");
        fillbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 7));
        fillbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fillbtn.setFocusPainted(false);
        fillbtn.setFocusable(false);
        fillbtn.setOpaque(true);
        fillbtn.setRolloverEnabled(false);
        fillbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillbtnActionPerformed(evt);
            }
        });

        addbtn.setBackground(new java.awt.Color(255, 102, 0));
        addbtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        addbtn.setForeground(java.awt.Color.white);
        addbtn.setText("A D D ");
        addbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 7));
        addbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addbtn.setRolloverEnabled(false);
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/back_white.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        buttonGroup3.add(maleradio);
        maleradio.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        maleradio.setForeground(new java.awt.Color(255, 255, 255));
        maleradio.setSelected(true);
        maleradio.setText("Male");

        buttonGroup3.add(femaleradio);
        femaleradio.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        femaleradio.setForeground(new java.awt.Color(255, 255, 255));
        femaleradio.setText("Female");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(idlbl)
                                    .addGap(18, 18, 18)
                                    .addComponent(idtf, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(fillbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(addresslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(addresstf, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(numlbl)
                                    .addGap(18, 18, 18)
                                    .addComponent(numtf, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(emaillbl, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(emailtf, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(genderlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(maleradio)
                                .addGap(18, 18, 18)
                                .addComponent(femaleradio))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lnamelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(lnametf, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fnamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fnametf, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1)))
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idlbl)
                    .addComponent(idtf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fillbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnametf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnamelbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnametf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnamelbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderlbl)
                    .addComponent(maleradio)
                    .addComponent(femaleradio))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numtf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numlbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addresstf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addresslbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailtf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emaillbl))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/cross.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setRolloverEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        table.setBackground(new java.awt.Color(172, 170, 170));
        table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        table.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "I.D", "First Name", "Last Name", "Contact No.", "Email", "Address", "Gender", "VIP Till "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        table.setGridColor(new java.awt.Color(51, 51, 51));
        table.setRequestFocusEnabled(false);
        table.setRowHeight(27);
        table.setShowGrid(true);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(0).setPreferredWidth(50);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(1).setPreferredWidth(100);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(2).setPreferredWidth(100);
            table.getColumnModel().getColumn(3).setResizable(false);
            table.getColumnModel().getColumn(3).setPreferredWidth(100);
            table.getColumnModel().getColumn(4).setResizable(false);
            table.getColumnModel().getColumn(4).setPreferredWidth(200);
            table.getColumnModel().getColumn(5).setResizable(false);
            table.getColumnModel().getColumn(5).setPreferredWidth(200);
            table.getColumnModel().getColumn(6).setResizable(false);
            table.getColumnModel().getColumn(6).setPreferredWidth(70);
            table.getColumnModel().getColumn(7).setResizable(false);
            table.getColumnModel().getColumn(7).setPreferredWidth(100);
        }

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("V I P  S T U D E N T S");

        searchtf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchtf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        searchtf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchtfMouseClicked(evt);
            }
        });
        searchtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtfActionPerformed(evt);
            }
        });

        combobox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "< Search By : >", "Student I.D", "First Name", "Last Name", "Gender", "Phone No.", "Address", "Email", "All Students" }));
        combobox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboboxMouseClicked(evt);
            }
        });
        combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxActionPerformed(evt);
            }
        });

        searchbtn.setBackground(new java.awt.Color(255, 102, 0));
        searchbtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        searchbtn.setForeground(java.awt.Color.white);
        searchbtn.setText("S E A R C H");
        searchbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 7));
        searchbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchbtn.setRolloverEnabled(false);
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(searchtf, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel3)
                                .addGap(59, 59, 59)))
                        .addGap(220, 220, 220)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combobox, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(searchtf, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void fnametfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnametfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnametfActionPerformed

    private void lnametfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnametfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnametfActionPerformed

    private void numtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numtfActionPerformed

    private void addresstfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addresstfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addresstfActionPerformed

    private void emailtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtfActionPerformed

    private void idtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtfActionPerformed

    private void fillbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillbtnActionPerformed
        if (idtf.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Enter Student I.D.");
        } else {
            Cipher cipher = new Cipher();
            String query = "SELECT * FROM student WHERE student_id = '" + cipher.encode(idtf.getText()) + "'";
            try {
                Connection con = ConnectionProvider.getconnection();
                Statement statement = con.createStatement();
                ResultSet result = statement.executeQuery(query);
                if (result.next()) {
                    fnametf.setText(cipher.decode(result.getString("student_fname")));
                    lnametf.setText(cipher.decode(result.getString("student_lname")));
                    numtf.setText(cipher.decode(result.getString("student_phone")));
                    addresstf.setText(cipher.decode(result.getString("student_address")));
                    emailtf.setText(cipher.decode(result.getString("student_email")));
                    char gender = cipher.decode(result.getString("student_sex")).charAt(0);
                    if (gender == 'M') {
                        maleradio.setSelected(true);
                    } else if (gender == 'F') {
                        femaleradio.setSelected(true);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "I.D : " + idtf.getText() + " is not registered.");
                }
                con.close();
                statement.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Something Went Wrong !");
            }
        }
    }//GEN-LAST:event_fillbtnActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed

        if (idtf.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Enter Student I.D.");
        } else {
            int dialogResult = JOptionPane.showConfirmDialog(this, "Membership Fee : $10\nFees Paid?", "Fee Confirmation", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                Vip vip = new Vip(idtf.getText());
                try {
                    vip.addstudent();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex);
                }
                query = "SELECT vip_id,student_fname,student_lname,student_phone,student_email,student_address,student_sex,duration FROM  vips  JOIN student ON student_id=vip_id";
                printtable();
            } else {
                JOptionPane.showMessageDialog(this, "Membership Rejected.");
            }
            idtf.setText("");
            fnametf.setText("");
            lnametf.setText("");
            maleradio.setSelected(true);
            numtf.setText("");
            addresstf.setText("");
            emailtf.setText("");
        }

    }//GEN-LAST:event_addbtnActionPerformed

    private void removebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removebtnActionPerformed
        if (idtf.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Enter Student I.D ...");
        } else {
            Vip vip = new Vip(idtf.getText());
            try {
                vip.removestudent();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
            idtf.setText("");
            fnametf.setText("");
            lnametf.setText("");
            maleradio.setSelected(true);
            numtf.setText("");
            addresstf.setText("");
            emailtf.setText("");
            query = "SELECT vip_id,student_fname,student_lname,student_phone,student_email,student_address,student_sex,duration FROM  vips  JOIN student ON student_id=vip_id";
            printtable();
        }
    }//GEN-LAST:event_removebtnActionPerformed

    private void comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxActionPerformed

    private void searchtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtfActionPerformed
     }//GEN-LAST:event_searchtfActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        idtf.setText("");
        fnametf.setText("");
        lnametf.setText("");
        maleradio.setSelected(true);
        numtf.setText("");
        addresstf.setText("");
        emailtf.setText("");
        Cipher cipher = new Cipher();
        if (searchtf.getText().equals("") && combobox.getSelectedIndex() != 8) {
            JOptionPane.showMessageDialog(this, "Please Fill Search Bar!!!");
        } else {
            if (combobox.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Please Select Option To Filter Result!!!");
            } else {
                if (combobox.getSelectedIndex() == 1) {
                    query = "SELECT vip_id,student_fname,student_lname,student_phone,student_email,student_address,student_sex,duration FROM  vips  JOIN student ON student_id=vip_id WHERE student_id='" + cipher.encode(searchtf.getText()) + "'";
                }
                if (combobox.getSelectedIndex() == 2) {
                    query = "SELECT vip_id,student_fname,student_lname,student_phone,student_email,student_address,student_sex,duration FROM  vips  JOIN student ON student_id=vip_id WHERE student_fname='" + cipher.encode(searchtf.getText()) + "'";
                }
                if (combobox.getSelectedIndex() == 3) {
                    query = "SELECT vip_id,student_fname,student_lname,student_phone,student_email,student_address,student_sex,duration FROM  vips  JOIN student ON student_id=vip_id WHERE student_lname='" + cipher.encode(searchtf.getText()) + "'";
                }
                if (combobox.getSelectedIndex() == 4) {
                    query = "SELECT vip_id,student_fname,student_lname,student_phone,student_email,student_address,student_sex,duration FROM  vips  JOIN student ON student_id=vip_id WHERE student_sex='" + cipher.encode(searchtf.getText()) + "'";
                }
                if (combobox.getSelectedIndex() == 5) {
                    query = "SELECT vip_id,student_fname,student_lname,student_phone,student_email,student_address,student_sex,duration FROM  vips  JOIN student ON student_id=vip_id WHERE student_phone='" + cipher.encode(searchtf.getText()) + "'";
                }
                if (combobox.getSelectedIndex() == 6) {
                    query = "SELECT vip_id,student_fname,student_lname,student_phone,student_email,student_address,student_sex,duration FROM  vips  JOIN student ON student_id=vip_id WHERE student_address='" + cipher.encode(searchtf.getText()) + "'";
                }
                if (combobox.getSelectedIndex() == 7) {
                    query = "SELECT vip_id,student_fname,student_lname,student_phone,student_email,student_address,student_sex,duration FROM  vips  JOIN student ON student_id=vip_id WHERE student_email='" + cipher.encode(searchtf.getText()) + "'";
                }
            }
        }
        if (combobox.getSelectedIndex() == 8) {
            query = "SELECT vip_id,student_fname,student_lname,student_phone,student_email,student_address,student_sex,duration FROM  vips  JOIN student ON student_id=vip_id";
        }
        printtable();
        searchtf.setText("");
    }//GEN-LAST:event_searchbtnActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int row = table.getSelectedRow();
        TableModel model = table.getModel();
        idtf.setText(model.getValueAt(row, 0).toString());
        fnametf.setText(model.getValueAt(row, 1).toString());
        lnametf.setText(model.getValueAt(row, 2).toString());
        numtf.setText(model.getValueAt(row, 3).toString());
        emailtf.setText(model.getValueAt(row, 4).toString());
        addresstf.setText(model.getValueAt(row, 5).toString());
        char gender = (model.getValueAt(row, 6).toString()).charAt(0);
        if (gender == 'M') {
            maleradio.setSelected(true);
        } else if (gender == 'F') {
            femaleradio.setSelected(true);
        }
    }//GEN-LAST:event_tableMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        LibrarianDashboard ld;
        try {
            ld = new LibrarianDashboard();
            ld.show();
            dispose();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }

    }//GEN-LAST:event_jLabel9MouseClicked

    private void searchtfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchtfMouseClicked
        idtf.setText("");
        fnametf.setText("");
        lnametf.setText("");
        maleradio.setSelected(true);
        numtf.setText("");
        addresstf.setText("");
        emailtf.setText("");
    }//GEN-LAST:event_searchtfMouseClicked

    private void comboboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboboxMouseClicked
        idtf.setText("");
        fnametf.setText("");
        lnametf.setText("");
        maleradio.setSelected(true);
        numtf.setText("");
        addresstf.setText("");
        emailtf.setText("");    }//GEN-LAST:event_comboboxMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageVips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageVips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageVips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageVips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ManageVips().setVisible(true);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JLabel addresslbl;
    private javax.swing.JTextField addresstf;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JLabel emaillbl;
    private javax.swing.JTextField emailtf;
    private javax.swing.JRadioButton femaleradio;
    private javax.swing.JButton fillbtn;
    private javax.swing.JLabel fnamelbl;
    private javax.swing.JTextField fnametf;
    private javax.swing.JLabel genderlbl;
    private javax.swing.JLabel idlbl;
    private javax.swing.JTextField idtf;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lnamelbl;
    private javax.swing.JTextField lnametf;
    private javax.swing.JRadioButton maleradio;
    private javax.swing.JLabel numlbl;
    private javax.swing.JTextField numtf;
    private javax.swing.JButton removebtn;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField searchtf;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
